# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"


BBFILE_COLLECTIONS += "aaeon-mtk"
BBFILE_PATTERN_aaeon-mtk = "^${LAYERDIR}/"
BBFILE_PRIORITY_aaeon-mtk = "7"

LAYERSERIES_COMPAT_aaeon-mtk = "kirkstone"